### ISSUE TITLE
Problems running callback server on Windows

### ISSUE THREAD

**Issue by sipickles** [athera-io/athera-python#14]
When running generate_jwt.py on windows (py2.7 or 3.7) this problem is encountered:

```
(AtheraPY37) D:\____Athera\athera-python-master\athera\auth>python generate_jwt.py
2018-11-01 12:59:04,264 - ATHERA - INFO - 1876 - Using https://id.athera.io/ https://public.athera.io
2018-11-01 12:59:04,264 - ATHERA - INFO - 1876 - Authorize called
2018-11-01 12:59:04,264 - ATHERA - INFO - 1876 - Setup CallbackServer
Traceback (most recent call last):
  File "generate_jwt.py", line 74, in <module>
    main()
  File "generate_jwt.py", line 55, in main
    authorize_url = client.authorize()
  File "D:\____Athera\athera-python-master\athera\auth\oauth_client.py", line 95, in authorize
    self.start_callback_server()
  File "D:\____Athera\athera-python-master\athera\auth\oauth_client.py", line 82, in start_callback_server
    self.server.start()
  File "c:\python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\python37\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\python37\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python37\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

(AtheraPY37) D:\____Athera\athera-python-master\athera\auth>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python37\Lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python37\Lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```
Looks to be: 
https://stackoverflow.com/questions/30081961/multiprocessing-works-in-ubuntu-doesnt-in-windows

**Comment by sipickles** [comment]
Fixed by https://github.com/athera-io/athera-python/commit/436360da9564f092f743424215f2b732eeb1b0c1
